version: 2
updates:
  #  https://devblogs.microsoft.com/dotnet/using-dependabot-to-manage-dotnet-sdk-updates/
  - package-ecosystem: "dotnet-sdk"
    directory: /
    schedule:
      interval: "weekly"
      day: "tuesday"
    open-pull-requests-limit: 1

  # NuGet package updates
  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: "weekly"
      day: "sunday"
    open-pull-requests-limit: 3
    rebase-strategy: disabled
    groups:
      microsoft-sbom:
        patterns: ['Microsoft.Sbom.Targets']
      Microsoft.NET.Test.Sdk:
        patterns: ['Microsoft.NET.Test.Sdk']
      testcontainers:
        patterns: [ 'Testcontainers', 'Testcontainers.*']
      microsoft:
        patterns: [Microsoft.*, System.*]
      xunit:
        patterns: [xunit.*]
      all-dependencies:
        patterns: ['*']

# Github Actions updates
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: "weekly"
      day: "sunday"
    open-pull-requests-limit: 3
    rebase-strategy: disabled
