on:
  workflow_call:
    inputs:
      runs-on:
        required: false
        type: string
        default: 'ubuntu-latest'
    secrets:
      NUGET_KEY:
        required: true
permissions: read-all

jobs:
  nuget-publish:
    if: ${{ github.event_name != 'pull_request' && github.repository == 'microcks/microcks-aspire' }}
    runs-on: ${{ inputs.runs-on }}
    steps:
    - name: ðŸ“¥ Download artifact
      uses: actions/download-artifact@v6
      with:
        name: nugets_${{ inputs.runs-on }}
        path: nuget_packages

    - name: ðŸš€ Publish Package to NuGet
      run: dotnet nuget push nuget_packages/**/*.nupkg  `
        -k ${{ secrets.NUGET_KEY }}  `
        --skip-duplicate -n `
        -s https://api.nuget.org/v3/index.json
      shell: pwsh
